### ISSUE TITLE
Not listed in Community gateways

### ISSUE THREAD

**Issue by xpavp03** [unoapp-dev/omnipay-moneris#1]
Hi, I'm considering using your package but I wonder, why it isn't listed in the official overview of implemented gateways? AFAIK, it's the only one that supports version 3.

https://omnipay.thephpleague.com/gateways/community/

**Comment by unoapp-dev** [comment]
@xpavp03 
Its added now.

Please check it here.
https://github.com/thephpleague/omnipay#payment-gateways

Thank you.
